// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package entity

import (
	"context"
)

const getUsers = `-- name: GetUsers :many
SELECT dni, name, lastname, rol_code, gender, image, address, phone, email, password, created_at FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Dni,
			&i.Name,
			&i.Lastname,
			&i.RolCode,
			&i.Gender,
			&i.Image,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
