// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cash struct {
	Code        uuid.UUID
	UserDni     string
	Amount      float32
	State       bool
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Category struct {
	Code        uuid.UUID
	Name        string
	Description sql.NullString
}

type Contact struct {
	Code        uuid.UUID
	Name        string
	Type        string
	Email       sql.NullString
	Phone       sql.NullString
	Address     sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Expense struct {
	Code        uuid.UUID
	Description string
	UserDni     string
	CashCode    uuid.UUID
	Total       float32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Material struct {
	Code         uuid.UUID
	Name         string
	Description  sql.NullString
	CategoryCode uuid.UUID
	CreatedAt    sql.NullTime
}

type Purchase struct {
	ExpenseCode uuid.UUID
	ContactCode uuid.UUID
	VoucherNum  sql.NullString
}

type PurchaseDetail struct {
	PurchaseCode uuid.UUID
	MaterialCode uuid.UUID
	Quantity     int32
	Price        float32
}

type Role struct {
	Code        uuid.UUID
	Name        string
	Description sql.NullString
}

type Stock struct {
	MaterialCode uuid.UUID
	Quantity     int32
	State        string
	UpdatedAt    time.Time
}

type User struct {
	Dni       string
	Name      string
	Lastname  string
	RolCode   uuid.UUID
	Gender    string
	Image     sql.NullString
	Address   sql.NullString
	Phone     sql.NullString
	Email     string
	Password  string
	CreatedAt time.Time
}
